-- Custom floor editor ("EDITOR DE PISOS" en Configuración). Run once before
-- deploying the custompisos.js feature. Each JSON column stores one slice of
-- a hand-authored floor; the game/editor combine them on the fly for
-- import/export instead of persisting a merged blob anywhere.
create table if not exists public.config_custom_piso (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  nivel text null,
  enemigos json null,
  chests_keys_traps json null,
  assets json null,
  tiles_doors json null,
  interiors json null,
  salas json null,
  constraint config_custom_piso_pkey primary key (id)
) TABLESPACE pg_default;

comment on column public.config_custom_piso.nivel is
  'Free-text floor-level match: single number, comma list and/or ranges (e.g. "3,5,8-10"). Empty/null = any level.';
comment on column public.config_custom_piso.tiles_doors is
  'Grid topology (cols/rows/cells) plus door tiles placed on it. No images: cells reference existing config_floor tile ids.';
comment on column public.config_custom_piso.assets is
  'World-object/decoration instances placed on the grid, referencing existing config_world_object rows by object_key.';
comment on column public.config_custom_piso.enemigos is
  'Enemy instances placed on the grid, referencing existing enemy_detail rows.';
comment on column public.config_custom_piso.chests_keys_traps is
  'Chests, keys and traps placed on the grid. Traps carry a damage-dice expression and a stackable-effects list.';
comment on column public.config_custom_piso.interiors is
  'Nested piso drafts (same shape as this table''s columns) keyed by the placing door-asset instance id.';
comment on column public.config_custom_piso.salas is
  'Optional labeled rectangles the designer drew to group/organize content on the grid.';
