const SUPABASE_TABLE='user_pj';
function supabaseConfig(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Faltan SUPABASE_URL o SUPABASE_ANON_KEY');return{url:url.replace(/\/$/,''),key}}
function headers(key){return{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'}}
function score(pj={}){const eq=Object.values(pj.equipment||{}).filter(Boolean),ilvl=eq.reduce((a,i)=>a+(+i.itemLevel||+i.ilvl||0),0),loot=(pj.inventory||[]).length*3+(+pj.gold||0)/10,skills=(pj.knownSkills||[]).length*8;return Math.round(((+pj.level||1)*100)+((+pj.bestFloor||+pj.floor||1)*75)+ilvl*12+loot+skills)}
function clean(b){const pj=b.pj_json||b.pj||{};return{nombre:b.nombre||null,pj_name:b.pj_name||pj.name||'Sin nombre',pj_json:pj,pj_status:b.pj_status||pj.status||'alive',pj_score:b.pj_score??score(pj),last_use:b.last_use||null}}
module.exports=async(req,res)=>{try{const{url,key}=supabaseConfig();
 if(req.method==='GET'){const nombre=req.query?.nombre,status=req.query?.status;let q=`select=id,created_at,nombre,pj_name,pj_json,pj_status,pj_score,last_use&order=pj_score.desc`;if(nombre)q+=`&nombre=eq.${encodeURIComponent(nombre)}`;if(status)q+=`&pj_status=eq.${encodeURIComponent(status)}`;const r=await fetch(`${url}/rest/v1/${SUPABASE_TABLE}?${q}`,{headers:headers(key)}),data=await r.json();if(!r.ok)return res.status(r.status).json(data);return res.status(200).json(data)}
 if(req.method==='POST'){const r=await fetch(`${url}/rest/v1/${SUPABASE_TABLE}`,{method:'POST',headers:{...headers(key),Prefer:'return=representation'},body:JSON.stringify(clean(req.body||{}))}),data=await r.json();if(!r.ok)return res.status(r.status).json(data);return res.status(200).json(Array.isArray(data)?data[0]:data)}
 if(req.method==='PUT'){const id=req.query?.id||req.body?.id;if(!id)return res.status(400).json({error:'Falta id'});const r=await fetch(`${url}/rest/v1/${SUPABASE_TABLE}?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...headers(key),Prefer:'return=representation'},body:JSON.stringify(clean(req.body||{}))}),data=await r.json();if(!r.ok)return res.status(r.status).json(data);return res.status(200).json(Array.isArray(data)?data[0]:data)}
 res.setHeader('Allow','GET, POST, PUT');return res.status(405).json({error:'Método no permitido'});
}catch(e){return res.status(500).json({error:e.message})}};
